import Link from "next/link";

const CookiePage = () => {

    return (
        <div className="overflow-hidden px-3 md:px-6 lg:px-10">
            <div className="w-full max-w-[1240px] lg:mx-auto my-8 md:my-12 lg:my-24 z-0 bg-background">
                <h1 className="font-header font-semibold text-3xl lg:text-4xl text-center mb-4 md:mb-6 lg:mb-8">Cookie Policy</h1>
                <p className="font-body text-base md:text-lg lg:text-xl mx-auto mb-4 md:mb-6 lg:mb-8">
                    <span className="font-semibold">Last Updated: </span>26 February 2024
                    <br /><br />
                    Welcome to the Website of the Art Collection of Laszlo Pecsi! We use cookies to improve your experience on our site and to understand how our site is being used. This helps us provide a more personalized service to you.
                    <br /><br />
                    <span className="font-semibold">What Are Cookies?</span>
                    <br /><br />
                    Cookies are small text files that are placed on your device by websites that you visit. They are widely used to make websites work, or work more efficiently, as well as to provide information to the owners of the site.
                    <br /> <br />
                    <span className="font-semibold">How We Use Cookies</span>
                    <br /><br />
                    We use Google Analytics, a service provided by Google, Inc., to gather and analyze information about your use of our website. Google Analytics uses cookies to collect information such as how often users visit our site, what pages they visit, and what other sites they used prior to coming to our site.
                    <br /> <br />
                    <span className="font-semibold">Google Analytics Cookies</span>
                    <br /><br />
                    _ga: Used to distinguish users. Expires after 2 years.
                    <br />
                    _gid: Used to distinguish users. Expires after 24 hours.
                    <br />
                    _gat: Used to throttle request rate. Expires after 1 minute.
                    <br /><br />
                    The information generated by these cookies about your use of our website (including your IP address) will be transmitted to and stored by Google. Google uses this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators, and providing other services relating to website activity and internet usage.
                    <br /> <br />
                    <span className="font-semibold">How to Control Cookies</span>
                    <br /><br />
                    You can control and/or delete cookies as you wish – for details, see <Link href='https://www.aboutcookies.org/' target="_blank" className="text-primaryOrange underline hover:text-[#DC2F02] duration-150 transition-all">aboutcookies.org</Link>. You can delete all cookies that are already on your computer and you can set most browsers to prevent them from being placed. If you do this, however, you may have to manually adjust some preferences every time you visit a site and some services and functionalities may not work.
                    <br /><br />
                    <span className="font-semibold">Your Consent</span>
                    <br /><br />
                    By using our website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.
                    <br /><br />
                    <span className="font-semibold">Changes to Our Cookie Policy </span>
                    <br /><br />
                    We may update this Cookie Policy from time to time. Please check back regularly to see any updates or changes to our Cookie Policy.
                    <br /><br />
                    <span className="font-semibold">Contact Us</span>
                    <br /><br />
                    If you have any questions about our use of cookies, please  <Link href='/contact' target="_blank" className="text-primaryOrange underline hover:text-[#DC2F02] duration-150 transition-all">Contact us</Link>.
                </p>
            </div>
        </div>
    );

};

export default CookiePage;